import { SchoolId, SchoolSettings, SchoolTheme, SchoolWebsite } from './types';

export const schoolThemes: Record<SchoolId, SchoolTheme> = {
  'springfield': {
    name: 'Delhi Public Academy',
    id: 'springfield',
    primary: '#1e40af',
    secondary: '#3b82f6',
    accent: '#f59e0b',
    background: '#ffffff',
    surface: '#f8fafc',
    text: '#1e293b',
    textSecondary: '#475569',
    gradient: 'linear-gradient(135deg, #1e40af 0%, #3b82f6 50%, #60a5fa 100%)',
    fontFamily: 'Georgia, serif',
    borderRadius: '0.5rem',
  },
  'green-valley': {
    name: 'Green Valley International School',
    id: 'green-valley',
    primary: '#166534',
    secondary: '#22c55e',
    accent: '#d97706',
    background: '#ffffff',
    surface: '#f0fdf4',
    text: '#1e293b',
    textSecondary: '#475569',
    gradient: 'linear-gradient(135deg, #166534 0%, #22c55e 50%, #86efac 100%)',
    fontFamily: '"Segoe UI", sans-serif',
    borderRadius: '1rem',
  },
  'royal-heritage': {
    name: 'Royal Heritage School',
    id: 'royal-heritage',
    primary: '#9a3412',
    secondary: '#ea580c',
    accent: '#eab308',
    background: '#ffffff',
    surface: '#fef3c7',
    text: '#1e293b',
    textSecondary: '#475569',
    gradient: 'linear-gradient(135deg, #9a3412 0%, #ea580c 50%, #fbbf24 100%)',
    fontFamily: '"Palatino Linotype", serif',
    borderRadius: '0.25rem',
  },
  'future-tech': {
    name: 'Future Tech Academy',
    id: 'future-tech',
    primary: '#4f46e5',
    secondary: '#8b5cf6',
    accent: '#06b6d4',
    background: '#0f172a',
    surface: '#1e293b',
    text: '#f1f5f9',
    textSecondary: '#cbd5e1',
    gradient: 'linear-gradient(135deg, #4f46e5 0%, #8b5cf6 50%, #06b6d4 100%)',
    fontFamily: '"Inter", sans-serif',
    borderRadius: '0.75rem',
  },
};

export const schoolSettings: Record<SchoolId, SchoolSettings> = {
  'springfield': {
    schoolName: 'Delhi Public Academy',
    address: 'Sector 15, Rohini, New Delhi - 110085',
    phone: '+91 11 4567 8900',
    email: 'info@delhipublicacademy.in',
    establishedYear: 1985,
    motto: 'Vidya Dadaati Vinayam',
    principalName: 'Dr. Anjali Sharma',
    totalStudents: 1250,
    totalTeachers: 85,
    academicYear: '2025-2026',
  },
  'green-valley': {
    schoolName: 'Green Valley International School',
    address: 'Electronic City, Phase 2, Bangalore - 560100',
    phone: '+91 80 2345 6789',
    email: 'contact@greenvalley.in',
    establishedYear: 2001,
    motto: 'Satyam Shivam Sundaram',
    principalName: 'Mr. Rajesh Kumar',
    totalStudents: 980,
    totalTeachers: 72,
    academicYear: '2025-2026',
  },
  'royal-heritage': {
    schoolName: 'Royal Heritage School',
    address: 'Alipore, Kolkata - 700027',
    phone: '+91 33 3456 7890',
    email: 'admissions@royalheritage.in',
    establishedYear: 1952,
    motto: 'Tamaso Ma Jyotirgamaya',
    principalName: 'Mr. Vikram Singh',
    totalStudents: 650,
    totalTeachers: 58,
    academicYear: '2025-2026',
  },
  'future-tech': {
    schoolName: 'Future Tech Academy',
    address: 'Hitech City, Madhapur, Hyderabad - 500081',
    phone: '+91 40 4567 8900',
    email: 'hello@futuretechacademy.in',
    establishedYear: 2018,
    motto: 'Technology for Tomorrow',
    principalName: 'Dr. Priya Reddy',
    totalStudents: 420,
    totalTeachers: 45,
    academicYear: '2025-2026',
  },
};

export const schoolWebsites: Record<SchoolId, SchoolWebsite> = {
  'springfield': {
    heroTitle: 'Welcome to Delhi Public Academy',
    heroSubtitle: 'Building Tomorrow\'s Leaders Through Excellence in Education Since 1985',
    aboutContent: 'Delhi Public Academy is a prestigious educational institution committed to providing world-class education. With state-of-the-art facilities, dedicated faculty, and a rich tradition of academic excellence, we prepare students for success in an ever-changing world.',
    missionStatement: 'To inspire lifelong learning and develop responsible citizens who contribute positively to society.',
    visionStatement: 'To be a leading educational institution that empowers students to achieve their full potential.',
    footerText: '© 2026 Delhi Public Academy. All rights reserved.',
    socialLinks: {
      facebook: '#',
      twitter: '#',
      instagram: '#',
      youtube: '#',
    },
  },
  'green-valley': {
    heroTitle: 'Green Valley International School',
    heroSubtitle: 'Where Nature Meets Knowledge — A Global Learning Experience',
    aboutContent: 'Green Valley International School offers a unique blend of academic rigor and environmental consciousness. Our campus nestled in beautiful surroundings provides the perfect environment for holistic development.',
    missionStatement: 'To foster global citizenship through sustainable education and cultural understanding.',
    visionStatement: 'To create environmentally conscious leaders who bridge cultures and communities.',
    footerText: '© 2026 Green Valley International School. All rights reserved.',
    socialLinks: {
      facebook: '#',
      twitter: '#',
      instagram: '#',
      youtube: '#',
    },
  },
  'royal-heritage': {
    heroTitle: 'Royal Heritage School',
    heroSubtitle: 'A Legacy of Excellence — Shaping Leaders of Distinction',
    aboutContent: 'Royal Heritage School stands as a beacon of traditional education with modern values. Our rigorous curriculum, combined with character development programmes, produces students of the highest calibre.',
    missionStatement: 'To uphold the finest traditions of education while preparing students for the challenges of the modern world.',
    visionStatement: 'To remain the premier institution for distinguished education and character formation.',
    footerText: '© 2026 Royal Heritage School. All rights reserved.',
    socialLinks: {
      facebook: '#',
      twitter: '#',
      instagram: '#',
      youtube: '#',
    },
  },
  'future-tech': {
    heroTitle: 'Future Tech Academy',
    heroSubtitle: 'Where Innovation Meets Education — Preparing Students for the Digital Age',
    aboutContent: 'Future Tech Academy reimagines education for the 21st century. Our STEM-focused curriculum, maker spaces, and AI-powered learning tools create an immersive tech experience that prepares students for careers in technology.',
    missionStatement: 'To democratize access to cutting-edge technology education and foster innovation at every level.',
    visionStatement: 'To be the global standard for technology-integrated education.',
    footerText: '© 2026 Future Tech Academy. All rights reserved.',
    socialLinks: {
      facebook: '#',
      twitter: '#',
      instagram: '#',
      youtube: '#',
    },
  },
};

export const SCHOOL_IDS: SchoolId[] = ['springfield', 'green-valley', 'royal-heritage', 'future-tech'];

export const getSchoolInfo = (id: SchoolId) => ({
  theme: schoolThemes[id],
  settings: schoolSettings[id],
  website: schoolWebsites[id],
});